example:
  property: I AM THE DEFAULT
spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    testWhileIdle: true
    validationQuery: SELECT 1
  database:
    driverClassName: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ostock
            client-authentication-method: client_secret_basic
            client-secret: Tw5yp3K8Rps0aKlU2f4gg188Qf1l3YGO
            authorization-grant-type: authorization_code
            scope: openid, profile, email
      resourseserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/spmia-realm
          jwk-set-uri: ${spring.security.oauth2.resourseserver.jwt.issuer-uri}/protocol/openid-connect/certs


jwt:
  auth:
    converter:
      resource-id: ostock
      principle-attribute: preferred_username

server:
  port: '8072'
management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: 'http://eurekaserver:8070/eureka/'
